web:
  #build: .
  image: matteosister/phoenix-elm:1.0.0
  volumes:
    - .:/code
  working_dir: /code
  ports:
    - 4000:4000
  links:
    - db

db:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: "elm_list"
